ARRAY BIDIMENSIONAL

In [21]:
import numpy as np

list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)

print (arr2d)


Más detallaes de numpy.ndarrray

Al momento de crear el ndarray, podemos especificar el tipo de dato:

In [22]:
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Y también podemos cambiar el tipo de dato:

In [23]:
#convertir a enteros nuevamente
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Una diferencia importante entre listas y np.ndarrays es que una lista puede almacenar objetos de diferentes tipos de datos, mientras que un np.array debe ser consistente en el tipo de dato que almacena. Esto se debe al deseo que tenemos por realizar operaciones vectorizadas.

Sin embargo, sí existe una forma de mantener la ambigüedad en el tipo de dato de nuestro array. Esto lo podemos logar si especificamos que el tipo de dato es object

In [25]:
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj



array([1, 'a'], dtype=object)

Por último: podemos convertir un ndarray a una lista en cualquier momento utilziando el método tolist()

In [26]:
lista = arr1d_obj.tolist()
lista

[1, 'a']

O bien,

In [30]:
import numpy as np

list(numpy.ndarray)

NameError: name 'numpy' is not defined